name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, edited]

  workflow_dispatch:

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      # - name: Set up the environment
      #   uses: ./.github/actions/setup-poetry-env

      # - name: Run checks
      #   run: poetry run invoke check
